### PR TITLE
Implement quick and dirty error message solution plus a few additional accessibility fixes

### LINKED ISSUE #563: Toast duration field doesn't have a minimum or maximum value set
All of the stepper fields in the settings dialog have a minimum and maximum value set that is enforced, **except for the toast duration setting**. As a result, if you erase all of the text in the toast duration field you get the error message "Select a value between and "

Image

In contrast, the border radius field has it working correctly:

Image

If you want to put in limiters for it, SettingsComponent.tsx is the first stop:

Currently, the duration component looks like this:

```
<NumberInput
	label="Duration (ms)"
	defaultValue={dirtySettings.toastDuration}
	isValid={settings.isValid(
		"toastDuration",
		dirtySettings.toastDuration
	)}
	onChange={(value) => {
		handleChange("toastDuration", value);
	}}
	onBlur={handleBlur}
/>
```

Mirroring the other components, an updated version would look something like:

```
<NumberInput
	label="Duration (ms)"
	defaultValue={dirtySettings.toastDuration}
        min={1}
	max={120000}
	isValid={settings.isValid(
		"toastDuration",
		dirtySettings.toastDuration
	)}
	onChange={(value) => {
		handleChange("toastDuration", value);
	}}
	onBlur={handleBlur}
/>
```

I tried updating it there and that's not enough to make it work fully. I think the next spot that needs to be updated is settingsSchema.ts:

```
// Notifications
	enableNotifications: z.boolean().default(true),
        ...
	toastDuration: z.number().default(5000),
```

Mirroring others in the settings  schema, a replacement might look like (pardon the formatting, I did in the Git issue editor):

```
// Notifications
	enableNotifications: z.boolean().default(true),
        ...
	toastDuration: z
                                    .number()
                                    .default(5000)
                                   .refine((value) => isWithinRange(value, 1, 120000)),
```

I'd submit a pull request for it, but I'm not sure what range you have in mind.

### PR DESCRIPTION
**Pull request by bacall213**
1. Implement the quick and dirty solution from #563 
2. Add a few minor CSS tweaks to keep text boxes from shuffling around when receiving and losing focus

### CODE REVIEW

**Comment by bacall213** [comment]
I've been playing around with this a bit more and I have some additional improvements to add when it comes to contrast and focus. I also think I found a way to get the errors announced properly. Setting the alert div to role="alert" and aria-live="polite" is one part of it, and then passing in the box label to the error so the error message has context associated with it is the other part. The resulting readout to screen readers is is something like "Border radius (px) Please enter a value less than 72"

**Comment by david-tejada** [comment]
I think for the external links we could use an icon and then have the text "Opens in new tab" as a .sr-only span after the icon. I would create a component to simplify this.

```tsx
import { faExternalLink } from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";

export function ExternalLink({
	href,
	children,
}: {
	readonly href: string;
	readonly children: React.ReactNode;
}) {
	return (
		<a href={href} target="_blank" rel="noreferrer">
			{children} <FontAwesomeIcon icon={faExternalLink} aria-hidden="true" />
			<span className="sr-only">Opens in new tab</span>
		</a>
	);
}
```

You need to create a .sr-only class in index.css:

```css
.sr-only {
	position: absolute;
	width: 1px;
	height: 1px;
	padding: 0;
	margin: -1px;
	overflow: hidden;
	clip: rect(0, 0, 0, 0);
	white-space: nowrap;
	border-width: 0;
}
```

Then we can use it like this:

```tsx
<p className="small show-on-focus">
  Use a{" "}
  <ExternalLink href="https://developer.mozilla.org/en-US/docs/Web/CSS/color_value">
    CSS color string
  </ExternalLink>
  .
</p>
```

As for the other changes, you can add them to this PR since it's all related to accessibility or create a new one. Whatever you prefer.

**Comment by bacall213** [comment]
One of the lingering issues is that the toast notifications use an aria-hidden icon for reporting the state. This is mostly an issue for the list of hint statuses. The toast is set to role="alert" by default so it's being read by screen readers, but the actual useful values for the states aren't being read. I found a way to add aria-labels to them and reference the state variable, but since the toast doesn't receive focus (and I'm not sure that it should) the aria-labels aren't read. 

I'm not sure yet what the best way to solve this one is.

**Comment by bacall213** [comment]
The toast notifications look like they would be considered a [status message](https://www.w3.org/WAI/WCAG21/Understanding/status-messages.html) and shouldn't receive focus, but the underlying content still needs to be announced. Still trying to find a way to solve for that. 

After some more testing, the alert boxes don't need the extra div tags to work reliably so I'll remove them from the updated file in the pull request.

File: src/pages/settings/SettingsComponent.tsx [hunk 1]
```diff
@@ -18,6 +20,21 @@ let justSaved = false;
...
+	readonly children: React.ReactNode;
+}) {
+	return (
+		<a href={href} target="_blank" rel="noreferrer">
+			{children} <FontAwesomeIcon icon={faExternalLink} aria-hidden="true" />
+			<span className="sr-only">Opens in new tab</span>
+		</a>
+	);
+}
+
```
Comment (david-tejada) [inline src/pages/settings/SettingsComponent.tsx]: Better move this to its own file

**Comment by david-tejada** [comment]
I added a commit. It has nothing to do with your changes. I just noticed it and since it's related I added it here.

What's the status of this PR, are you going to make more changes or is it ready to merge? I want to make a release soon and I want to include it.

**Comment by bacall213** [comment]
Everything is stable in it, but give me another day to double-check if there's anything else that needs to be added and also to tune the regex and selector error box formatting so they're consistently sized while being flexible. That will help ensure they look like they were there from the start.

**Comment by david-tejada** [comment]
Sure, no problem. Just let me know when it's ready

**Comment by bacall213** [comment]
Alright, that should be good. Do you want any comparison screenshots for how the PR changes things? Or are you already checking on your end?

**Comment by david-tejada** [comment]
No need for that. I will check myself. Thanks for all the work!
